---
- hosts: all
  become: true

  vars:
    system:
      hostname: "services.home.chiasson.org"
      timezone: "Etc/UTC"
      ip: 192.168.50.3
    network:
      gateway: 192.168.50.1
      dns: 192.168.50.2

  handlers:

    - name: "Restart cockpit Socket"
      ansible.builtin.service:
        name: "cockpit.socket"
        state: "restarted"
      become: true

    - name: "Reboot system"
      ansible.builtin.reboot:
        reboot_timeout: 3600
      become: true

  tasks:

    - name: "setup hostname and timezone"
      include_role:
        name: cervoevo.homelab.base
      vars:
        hostname: "{{ system.hostname }}"
        timezone: "{{ system.timezone }}"

    - name: "Enable screen blanking service"
      include_role:
        name: cervoevo.homelab.console_blanking

    - name: "Enable tuned service"
      include_role:
        name: cervoevo.homelab.tuned_service

    - name: "Enable avahi service"
      include_role:
        name: cervoevo.homelab.avahi_service

    - name: "Enable chrony service"
      include_role:
        name: cervoevo.homelab.chrony_service


  # Add CLI packages
    - name: "Manage cli Packages"
      ansible.builtin.package:
        name:
          - "bash"
          - "bash-completion"
          - "tmux"
          - "wget"
          - "curl"
          - "bind9-next-utils"
          - "lsof"
          - "unzip"
        state: "present"
      become: true

    - name: "Enable cockpit service"
      include_role:
        name: cervoevo.homelab.cockpit_service

    - name: "Enable virtualisation service"
      include_role:
        name: cervoevo.homelab.virt_service
