---
- hosts: all
  become: true

  vars:
    system:
      hostname: "services.home.chiasson.org"
      timezone: "Etc/UTC"
      ip: 192.168.50.3
    network:
      gateway: 192.168.50.1
      dns: 192.168.50.2

  handlers:

    - name: "Restart cockpit Socket"
      ansible.builtin.service:
        name: "cockpit.socket"
        state: "restarted"
      become: true
      tags:
        - "cockpit"
        - "kvm"

    - name: "Reboot system"
      ansible.builtin.reboot:
        reboot_timeout: 3600
      become: true
      tags:
        - "network"

  tasks:

    - name: "setup hostname and timezone"
      include_role:
        name: cervoevo.homelab.base
      vars:
        hostname: "{{ system.hostname }}"
        timezone: "{{ system.timezone }}"

    - name: "Enable screen blanking service"
      include_role:
        name: cervoevo.homelab.console_blanking

    - name: "Enable tuned service"
      include_role:
        name: cervoevo.homelab.tuned_service

    - name: "Enable avahi service"
      include_role:
        name: cervoevo.homelab.avahi_service

  # Chrony
    - name: "Manage chrony Packages"
      ansible.builtin.package:
        name: "chrony"
        state: "present"
      become: true

    - name: "Manage chrony Services"
      ansible.builtin.service:
        name: "chronyd.service"
        state: "started"
        enabled: true
      become: true

  # Add CLI packages
    - name: "Manage cli Packages"
      ansible.builtin.package:
        name:
          - "bash"
          - "bash-completion"
          - "tmux"
          - "wget"
          - "curl"
          - "bind9-next-utils"
          - "lsof"
          - "unzip"
        state: "present"
      become: true

  # Manage Cockpit 
    - name: "Manage cockpit Packages"
      ansible.builtin.package:
        name:
          - "cockpit"
          - "cockpit-selinux"
          - "cockpit-sosreport"
        state: "present"
      become: true

    - name: "Manage cockpit Services"
      ansible.builtin.service:
        name: "cockpit.socket"
        state: "started"
        enabled: true
      become: true

    - name: "Manage cockpit Firewall Policy"
      ansible.posix.firewalld:
        service: "cockpit"
        state: "enabled"
        immediate: true
        permanent: true
      become: true

  # Manage performance cockpit
    - name: "Manage pcp Packages"
      ansible.builtin.package:
        name:
          - "pcp"
          - "cockpit-pcp"
        state: "present"
      become: true

    - name: "Manage pcp Services"
      ansible.builtin.service:
        name: "{{ item }}"
        state: "started"
      become: true
      loop:
        - "pmcd.service"
        - "pmlogger.service"

    - name: "Enable virtualisation service"
      include_role:
        name: cervoevo.homelab.virt_service
