---
- hosts: all
  become: true
  tasks:
  - name: Drop a name
    debug:
      msg: "Testing with ansible-pull - services.yml"

# Chrony
  - name: "Manage chrony Packages"
    ansible.builtin.package:
      name: "chrony"
      state: "present"
    become: true

  - name: "Manage chrony Services"
    ansible.builtin.service:
      name: "chronyd.service"
      state: "started"
      enabled: true
    become: true

# Add CLI packages
  - name: "Manage cli Packages"
    ansible.builtin.package:
      name:
        - "bash"
        - "bash-completion"
        - "tmux"
        - "wget"
        - "curl"
        - "bind9-next-utils"
        - "lsof"
        - "unzip"
      state: "present"
    become: true
